version: "3.9"

services:
  db:
    image: postgres:15
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

  redis:
    image: redis:7
    container_name: auth_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: 
      context: .
    container_name: auth_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db           
      - DB_PORT=5432
      - DB_USER=youruser
      - DB_PASS=yourpass
      - DB_NAME=authdb
      - REDIS_HOST=redis      # Add this so backend knows Redis hostname
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

volumes:
  pgdata:
